### PR TITLE
Added Dockerfiles for Marian

### PR DESCRIPTION
**Pull request by natgillin**
Following @ugermann footsteps , added basic Dockerfile to build Marian.

### CODE REVIEW

**Comment by tomekd** [comment]
Hi @natgillin ,

looks good, but can you adjust Dockerfiles to those tips: https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices ?

**Comment by natgillin** [comment]
Thanks @tomekd for pointing out the best practices!

I've updated the Dockerfiles accordingly.

**Comment by emjotde** [comment]
@tomekd Can you take another look and merge if you are satisfied?

**Comment by emjotde** [comment]
Great, thanks @natgillin

**Pull request merged**
