### PR TITLE
Add Nematus-style factor support

### PR DESCRIPTION
**Pull request by rihardsk**
This is #132 rebased onto current `master`.

### CODE REVIEW

**Comment by tomekd** [comment]
Looks good for me. I don't remember whether I ask about a model for regression tests? Can you provide one?

**Comment by rihardsk** [comment]
@tomekd not yet, I'll have to train something. I can't share the one I've used for now.

**Comment by tomekd** [comment]
@rihardsk:  Thanks!

**Comment by rihardsk** [comment]
Do you wan't to wait for the regression tests or can we merge before that? I think training the system might take a week or so. I'm a bit scared of having to deal with merge conflicts again.

**Comment by tomekd** [comment]
It can be a toy model with halved parameter sizes (eg. 512 instead of 1024 or even 256).  We don't care about a high BLEU score there.

If I find the time, I''' run amun-regression tests on this pull request. If they passed, I will merge it.

**Comment by hieuhoang** [comment]
personally, i don't mind you pushing anytime existing tests passes (or u have a good excuse why they fail).

you can add new tests later once it's been trained or when you want to protect certain features you need

**Comment by rihardsk** [comment]
@tomekd don't merge just yet. I noticed that I've broken the Nematus soft alignment feature.

On a related note, we should probably add some regression tests for the ` --return-nematus-alignment` flag.

**Comment by rihardsk** [comment]
Nevermind, I was looking at an older version. `--return-nematus-alignment` work's as expected with this PR.

**Comment by hieuhoang** [comment]
@rihardsk You should push your code if it's ready. I'm likely to do a big push soon, it will be a world of pain for you to merge afterwards

**Comment by rihardsk** [comment]
@hieuhoang afaik everything here is good to go. @tomekd said he'll merge this after he checks regression tests.

When I ran the tests there was a single sentence with a slightly different translation (we discussed this in the previous PR). Other than that, everything seemed ok.

**Comment by hieuhoang** [comment]
Tests passed and merged. I see no reason to delay any longer

**Comment by tomekd** [comment]
@rihardsk : Thanks!

**Pull request merged**
