### PR TITLE
support arbitrary versions of python for python bindings on linux and mac os

### PR DESCRIPTION
**Pull request by CatarinaSilva**
Changed the CMakeLists to compile the python bindings to Mac and to support different python versions.

@tomaspinho

### CODE REVIEW

**Comment by tomaspinho** [comment]
I'm available to update the README.md if the maintainer so desires.

**Comment by tomekd** [comment]
@hieuhoang : Can you check it because I haven't got any MacBook.

**Comment by hieuhoang** [comment]
can't, it's at my brother's place. I would assume the code is correct unless a regression test is broken or someone complains

**Comment by tomaspinho** [comment]
This was tested on Ubuntu with python 2.7 and 3.5 and on macOS with python 2.7 and 3.6, but please feel free to run your own tests! 😉

**Comment by hieuhoang** [comment]
@tomekd we should merge these changes. I can't think of a good reason not to

**Comment by hieuhoang** [comment]
Cheers Catarina & Tomas.

**Pull request merged**
